server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/family_health
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  springfox:
    documentation:
      swagger-ui:
        base-url: /api
  ai:
    openai:
      api-key: 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
      chat:
        model: gpt-3.5-turbo
  cloud:
    function:
      scan:
        enabled: false
jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: Kr8wKak/9wdnyQr5DxVOB9XCzHlSqjMUwAFErLxY4w8=
  refreshKey: RxQYdMPpgTjMENN8KvBWqg4IzPSyn4Z1uPGVS6GrSxA=
  resetKey: HxrOJXyXpQ/WfWOMa10/Q3ZLc2GJx6teNxjcaQr+/qc=

  